version: "3.1"
services:
  api:
    environment:
      - PREAMAR_DATABASE_URL=
      - SEX_DEBUG=true
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.api
    image: preamar:api
    working_dir: /PreAmar/api
    tty: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 8000:8000
    volumes:
      - ./:/PreAmar
    command: air
  front:
    environment:
      - SEX_DEBUG=true
    restart: always
    build: .
    image: preamar:front
    working_dir: /PreAmar
    tty: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 80:5000
      - 3000:3000
    volumes:
      - ./:/PreAmar
    command: yarn start
    links:
      - api:api
