version: "3.1"
services:
  api:
    environment:
      - PREAMAR_DATABASE_URL=
      - SEX_DEBUG=true
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.api
    image: preamar:api
    working_dir: /PreAmar/api
    tty: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 8000:8000
    volumes:
      - ./:/PreAmar
    command: go run .
  front:
    restart: always
    build: .
    image: preamar:front
    working_dir: /PreAmar
    tty: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 5000:5000
    volumes:
      - ./:/PreAmar
    command: serve -s build
    links:
      - api:api
