version: "3.1"
services:
  front:
    environment:
      - SEX_DEBUG=true
    restart: always
    build: .
    image: preamar:front
    working_dir: /PreAmar
    tty: true
    security_opt:
      - seccomp:unconfined
    ports:
      - 80:5000
      - 3000:3000
    volumes:
      - ./:/PreAmar
    command: yarn start
    links:
      - api:api
